# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 20
  - name: Product
    weight: 30
    hasChildren: true
  - parent: Product
    name: Indoor Light
    url: indoor-light/
  - parent: Product
    name: Outdoor Light
    url: outdoor-light/
  - name: Resources
    weight: 40
    hasChildren: true
  - parent: Resources
    name: Blog
    url: blog/
